### ISSUE TITLE
Gestures deprecated?

### ISSUE THREAD

**Issue by mv-anna** [leapmotion/LeapUnreal#11]
I wanted to use swipe gestures but realized, gestures are deprecated. Is there a specific reason to this, or is there a plan to reintegrate them in a different way?
If I still want to use swipe gesture, what is a good way to do this? Do you have any recommendations for me on this?

Thanks =]

**Comment by getnamo** [comment]
Yes gestures are fully deprecated with v4 SDK. It is generally recommended to directly interact with objects in the scene instead of using generic recognizes, but if you want implement a swipe recognized it is fairly easy to do.

E.g. if you wish to make a right/left swipe recognizer you'd first take the dot product between your view (camera) rotation Right vector and your normalozed hand velocity. Divide this by the magnitude of both vectors multiplied together. Finally take the inverse cosine to get the angle between the two vectors. See: http://onlinemschool.com/math/library/vector/angl/ for details of this math.

Now that you have the angle, compare it against some threshold e.g. 15degrees and viola you've detected a swipe. Nb: use negative right vector for left swipe angle for
