### ISSUE TITLE
Shifted Hands for L/R eyes in UE 4.18 (backport to 4.18 vs using old v2)

### ISSUE THREAD

**Issue by MDTxxx** [leapmotion/LeapUnreal#49]
Hello guys, I've just started with Leap in Unreal Engine and so far have been impressed with the response and accuracy of the device.

First I tested it out in the latest 4.22 but since I'd like to implement it with OSVR HDK2, both for ethical and aesthetical reasons, I was forced to downgrade to 4.18 where I was able to bring both plugins successfully together. I couldn't make any other Leap plugin version working there but the preinstalled v2.0 though. 

The Leap plugin v2.0 works great and to my liking, the only - yet significant, issue I have is the hands are shifted for each eye so that in effect they visually overlap in the composite image in my brain (which really hurts btw). So even though there is only one pair of hands, it appears there are two pairs, kind of.

I figured it must be some rendering issue, but I couldn't locate it in any blueprint that is being used in the process. I sense it's something simple, but I just don't know where to look.

Any help will be greatly appreciated.

Best regards,
Frantisek

**Comment by getnamo** [comment]
If you're using the v2.0 plugin for 4.18, the repository for that plugin is https://github.com/getnamo/leap-ue4, and since v3 is a complete rewrite, it may be more appropriate to raise issues there. That said there appears to be enough interest in UE 4.18-4.20 to look into maybe doing a few backports to have v3 support for those versions.

Regarding the issue, what type of hands are you using in v2? just regular floating ones, or are you trying e.g. image hands? For image hands there can be an IPD mismatch since the device has 40mm between sensors vs typical 60mm.

**Comment by MDTxxx** [comment]
Yep, I'm using the regular LeapFloatingHands with LeapRiggedEchoHands nested blueprint.
That sensor width difference sounds promising. Where do I set it?
