### ISSUE TITLE
Add BodyStateSelector Support (multiplayer replication)

### ISSUE THREAD

**Issue by getnamo** [leapmotion/LeapUnreal#6]
Basic breakdown

- [x] BodyState Selector component with replication toggle
  - [x] if owner has authority, generate data and replicate to server
  - [x] If owner doesn't have authority, receive data and set from received replication
- [x] replace anim bp skeleton default with BSSelector 
- [ ] Two device test confirmation

**Comment by getnamo** [comment]
deferred, maybe 3.1?

**Comment by maciejcybinski** [comment]
Hi, I would like to replicate hands in my project. Has this BodyStateSelector been ever developed?
Has anyone done a template with hands replication?

The idea would be probably to pass the frame data to a replicated struct and then poll from the server to animate the other person's hand. I just stared to work on Leap in Unreal and I am not sure what I should change in Animation instance to read the joints data not from local Leap Motion, but a potential replicated structure.

**Comment by getnamo** [comment]
This feature hasn't been implemented yet, but it's on the docket. If you need replication right now, use the ```LeapComponent``` approach https://github.com/leapmotion/LeapUnreal#leap-component-events and replicate the ```FLeapFrameData``` struct to your other client. There are some direct rigging examples you can find here: https://github.com/leapmotion/LeapUnreal/tree/master/Content/DirectRigging/LowPoly which use the LeapFrameData instead of the bodystate system.

**Comment by maciejcybinski** [comment]
Thanks, for your advise! Unfortunately I didn't have time to implement it in the current project, but hopefully the upcoming ones.

**Comment by getnamo** [comment]
Note to self: component replication appears to have complex logic. The data appears to target the wrong player character owner (own controlled instead of peer). TBC.

**Comment by evan2882** [comment]
Hello, I was trying to make the replication of leap motion hands work as well. Currently I am trying to multicast Lframe data to the client. The client does see the server's hands but it does not refresh as fast. It stays as one gesture for a couple seconds and then move to the next gesture. I am thinking maybe I am replicating too much data, since I am replicating the whole leap frame data struct whenever Leaptracking data is available(I set the variable as rep-notify). Have u managed to get the hands replication run smoothly? Any suggestions would be very helpful. Thanks!
