### ISSUE TITLE
custom gesture recognition?

### ISSUE THREAD

**Issue by hmihalis1** [leapmotion/LeapUnreal#62]
I was wondering if it would be possible to program the leap to recognize some common hand gestures like peace sign, middle finger, devil horns etc. 

Any idea if this is possible or what would be involved?

**Comment by JimSimons-UH** [comment]
@hmihalis1 thanks for the enquiry,
Essentially you would need to create something that recognised the hand tracking data coming from the Leap motion Controller so that when a particular hand shape was made the hand tracking data would match what you where expecting and be able to recognise it as the required shape.


See below for reference: 

https://blog.leapmotion.com/asl-tutor-teaching-sign-language-leap-motion-machine-learning/
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6210690/
https://www.youtube.com/watch?v=sPYWe_E_F5w
https://www.youtube.com/watch?v=myizHGv6nYI
