### ISSUE TITLE
Running from command line (-game)

### ISSUE THREAD

**Issue by andyfedak** [leapmotion/LeapUnreal#9]
Hey there, this might be something simple, but when I run my level from the command line (using the -game flag), the leap doesn't track my hands, while if I run from the editor (and hit play in VR), everything is good.  

Any thoughts on this?  I've been scouring the interwebs, but have not been able to find anything useful.

Thanks,
-andy

**Comment by getnamo** [comment]
You may need to recompile the plugin for development build. This is the same step as packaging for windows: https://github.com/leapmotion/LeapUnreal#windows, add a c++ class, change the compilation target to Development and hit compile. Plugin includes full source so it will compile as expected.

That said it might be a good idea to add development builds of the plugin so it will work out of the box. Ill tag this as an enhancement.

**Comment by andyfedak** [comment]
Would I need to recompile even if I'm not packaging the game?  I'm using the leap plugin for a VR install and would like to not have to package (I edit the position of the player spawn point when I get to the gallery within the editor).  

Just so we are on the same page, once I have the spawn point the way I like it in the space, I'm basically just opening the editor from the command line...ie ue4editor.exe "project file" -game via a .bat file.  I've not packaged anything yet.  

Does that make sense?  I'm sorry if this is confusing, I appreciate your help/work on this plugin very much:)
-a

**Comment by getnamo** [comment]
Since you wish to run the game without the editor (bat commandline -game does this), you need to have the plugin working for ```development``` mode (not ```development editor``` which is used when you open a project via .uproject). Normally this will automatically get compiled when a developer packages the game, but in your case you are running it from commandline so you need to manually recompile for development mode, at least once per major engine version (e.g. the current plugin for 4.19 engine version). None of the additional packaging steps are necessary, just the part that adds an arbitrary c++ class to your project (converting it to a c++ project) which allows it to recompile with the plugin source included, in the desired mode. Once you've done this once, it should work as expected.

**Comment by andyfedak** [comment]
Great.  That makes sense.  Thanks for your help!
